// wit/world.wit
package docs:calculator@0.1.0;

interface calculate {
    enum op {
        add,
        subtract,
        interest-rate,
    }
    eval-expression: func(op: op, x: s32, y: s32) -> s32;
    eval-expression-three-args: func(op: op, x: f32, y: u32, z: u32) -> f32;
    total-payable: func(rate: f32, amount: u32, years: u32) -> f32;
}

world calculator {
    export calculate;
    import docs:adder/add@0.1.0;
    import docs:subtractor/subtract@0.1.0;
}

world app {
    import calculate;
}